<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenDemo</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>3</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>true</rerunImmediately>
   <testSuiteGuid>056befce-98f1-4d95-b31b-f8120fa43536</testSuiteGuid>
   <testCaseLink>
      <guid>067ee9c3-3334-4039-ad14-a9f1c7d84112</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/Demo/DataDrivenDemo</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>ff77ec08-eb15-4eb4-a5be-acd97eb87bc5</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/credentials</testDataId>
      </testDataLink>
      <usingDataBindingAtTestSuiteLevel>true</usingDataBindingAtTestSuiteLevel>
      <variableLink>
         <testDataLinkId>ff77ec08-eb15-4eb4-a5be-acd97eb87bc5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>2f6c7ca5-2120-48d6-a298-a488424d2d8b</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>ff77ec08-eb15-4eb4-a5be-acd97eb87bc5</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>95c9fac6-d721-4769-9a1d-5b30ab806c89</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId></testDataLinkId>
         <type>DEFAULT</type>
         <value></value>
         <variableId>da490f89-5984-4a1c-ab0f-29d455da37c0</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
